lokalise/i18n-ally

- src/editor/extract.ts
See https://github.com/microsoft/vscode/pull/49081
This is important for plugins calling `vscode.executeCodeActionsProvider` command.
> Extract: Obey selection passed by vscode

- src/frameworks/laravel/index.ts
This should allow the extension to work with a couple of VS Code extensions that enable highlighting for Laravel Blade Template files, like https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade
> Update Laravel Framework to work with blade templates

- src/utils/File.ts
Restored the ability to newline at the end of file.  
See. d50fb6ea521bb22ddf1762097335dc8d408b943e
Thank you for wonderful and useful extension!
> fix: Write file with newline at the end of file

- src/frameworks/vue-sfc.ts
vue-i18n-loader is now maintained at @intlify/vue-i18n-loader
> add newer @intlify version of vue-i18n-loader

- examples/by-frameworks/ui5/webapp/i18n/i18n_en.properties
- examples/by-frameworks/ui5/webapp/manifest.json
- src/frameworks/index.ts
- src/frameworks/ui5.ts
This update is to allow i18n translations from "manifest.json"(descriptor file), in which the i18n keys will be in the format of  "{{key}}"
- updated to allow json file
- updated the usagematch regex and refactor templates to allow the above format key.
Please let me know in case of any issues. Thanks in advance!
> UI5 Framework update 2

- package.json
I struggled with this for a while when trying to enable the po/pot-parser in the current version of the plugin.
Adding `"i18n-ally.enabledParsers": ["pot"]` in settings resulted in `🧬 Enabled parsers: ` showing up in the logs, and no files were found. Changing this to `"i18n-ally.enabledParsers": ["po"]` on the other hand seems to work fine, and `🧬 Enabled parsers: po` shows up in the logs.
However, VSCode thinks the value should be `pot` rather than `po`, which is incorrect.
> Change settings definition for po-parser

- src/parsers/json.ts
- src/parsers/json5.ts
This PR updates JSON (and JSON5) parsers to respect `tabStyle` option, so it should fix #337.
This is the simplest solution I could think of, it may not be perfect and I'm open to suggestions to improve it.
> Fixed tabStyle being ignored when formatting JSON and JSON5

- locales/en.json
- src/commands/extractText.ts
Hi, thank you for this amazing extension!
This PR makes `config.keyPrefix` a bit more powerful - it will replace `{fileName}` with the current file name, and `{fileNameWithoutExt}` with the current file name without the extension.
Your vscode config includes:
```json
"i18n-ally.extract.keyPrefix": "{fileNameWithoutExt}.",
```
If you have a file called `MyFile.js` and extract the text "Hello World", the suggested key will be `MyFile.hello-world`.
> add support for {fileName} variable in config.keyPrefix

- locales/en.json
- package.json
- src/commands/extractText.ts
- src/core/Config.ts
Hi!
This PR adds an option to limit the length of the extracted key.
For instance, if you select a huge paragraph of text, and set `i18n-ally.extract.keyMaxLength` to `30`, then the key will be truncated to 30 characters (not counting the keyPrefix)
(also, I added ` `` ` as a character that should be trimmed about when extracting text because it's used as a quote in some languages)
> add extract.keyMaxLength option

- src/frameworks/flutter.ts
Hello,
_flutter_i18n_ supports not only `FlutterI18n.translate` but also some text widgets :
```dart
I18nText("your.key", child: Text(""))
I18nText("your.key", translationParams: {"user": "Flutter lover"})
I18nPlural("clicked.times", 1)
I18nPlural("clicked.times", 2, child: Text(""))
```
Here is an attempt to add support for them as well.
> feat: add fluter_i18n text widget shorthand

- src/frameworks/flutter.ts
fix #344
Support breaking line after `(` or `context,` : 
```dart
TextFormField(
decoration: InputDecoration(
border: OutlineInputBorder(),
labelText: FlutterI18n.translate(
context, "settings.authentication.token.label"),
),
```
In my files the second option (breaking after the comma) is never used by dartfm.
> fix(flutter) multiline regex at any place

- src/translators/engines/google.ts
This is the proposed fix mentioned in https://github.com/lokalise/i18n-ally/issues/531.
The Google API either wants you to use a permanent API key (which works with this solution) or get access tokens which expire + being OAuthed to Google Cloud to work with POST requests.
This will check if the user supplied a Google API key and use the correct endpoint/GET-request. If a key was supplied it will also use different parsing to accommodate the new response structure.
This will leave the behaviour as-is if the user doesn't supply a key.
I am not sure how this will work if a user in China supplies an API-key as I expect it to use the `apiRootIfUserSuppliedKey` which might be blocked?
> fix: utilize Google API key with new api endpoint

- src/translators/engines/google.ts
The protected API endpoint is a bit more specific with what it supports (compared to the free one).
This will hopefully improve user experience with automated translations by only using the first part (fr instead of fr-Fr) when providing a key.
By doing this you will get a successful response, without this you will get a 400 response.
This PR was made due to comments in https://github.com/lokalise/i18n-ally/issues/531 where two users noticed the 400 behavior.
> Improve Google Cloud protected API endpoint usage

- locales/en.json
- package.json
- src/core/Config.ts
- src/translators/engines/deepl.ts
DeepL has a free api as seen [here](https://www.deepl.com/en/docs-api/). The key for free api does not work on pro api and vice-versa.
This PR adds a `i18n-ally.translate.deepl.useFreeApi` boolean option to use that API instead of PRO plan.
> feat: allow using deepl api free plan

- package.json
- src/core/Config.ts
- src/core/Global.ts
This PR adds basic support for workspaces in VSCode. _(Should partly fix #411)_
VSCode already has a folder-based setting solution, for that to work, configuration would need to allow to be used there with the `scope` property in package.json
I also needed to change the `getConfig` function, to allow passing a scope. _Relatively new to class-based typescript - sorry if I made mistakes with privates || getter and setters._
Also, it would be helpful in the future to decide which settings are allowed to be overridden by folder and which must stay in root level. That way more settings could be adapted in the future, and even might refactor some of the extra getters I have added in this PR, for a more general solution.
> feat: support scoped `localesPaths` setting

- package.json
- yarn.lock
1. Add fluent-vue to the list of available frameworks in the VSCode config
2. Fix `@vue/compiler-sfc` trying to access `document` and throwing an error
> fix: fluent-vue fixes

- package.json
Change `expiremental` to `experimental`.
> fix: experimental typo

- .vscode/extensions.json
[`eamodio.tsl-problem-matcher`](https://marketplace.visualstudio.com/items?itemName=eamodio.tsl-problem-matcher) was renamed.
🤷 
VSCode won't complain about the missing extension.
Visit https://marketplace.visualstudio.com/items?itemName=eamodio.tsl-problem-matcher, see that it redirects.
> Rename `eamodio.tsl-problem-matcher` in extensions.json

- package.json
According to https://github.com/elk-zone/elk/pull/1597#issuecomment-1416037382,
the default language tag system is bcp47 but shows default as empty.
> fix: set bcp47 as default

- test/fixture-scripts/index.ts
In chasing down the Vue issues plaguing the build, I looked into this error message:
```
Installing extensions...
Extension 'johnsoncodehk.volar' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
Failed Installing Extensions: johnsoncodehk.volar
``` 
The extension has been renamed to `vue.volar`, as seen by [the redirect in the Marketplace](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar).
Simple rename. 
To be candid, I'm not sure whether/why this extension is needed at all.
Less cluttered error log.
```
yarn test:fixture
```
> Rename `johnsoncodehk.volar` extension

- package.json
- test/e2e/index.ts
- test/fixture-scripts/index.ts
- yarn.lock
The i18n-ally tests are failing, since the `source.vue` files are being given the language identifier of `plaintext` ([the default for unknown languages](https://code.visualstudio.com/docs/languages/overview#_language-identifier)).
There is an override in [`test/fixtures/vue/.vscode/settings.json`](https://github.com/lokalise/i18n-ally/blob/67329128e82522dacc1d8d84fdb9f1dfdfbd79fd/test/fixtures/vue/.vscode/settings.json#L9-L11), but that is ignored unless `vue` is a known identifier.
Previously, `i18n-ally` used the `johnsoncodehk.volar` extension to add recognition of the `vue` language identifier. At some point, [`johnsoncodehk.volar` was renamed to `vue.volar`](https://github.com/lokalise/i18n-ally/pull/908). But `vue.volar` cannot be installed on VSCode v1.52.0:
```
Installing …
```
> Bump version of VSCode used in tests

- README.md
Distribute new versions of the extension to the developers.
The main blocker is that both official and open VCX marketplaces have denied the new release, because of SVG links within the README:
An official marketplace threw an error:
> Error processing 'Lokalise.i18n-ally' SVG reference in file '/extension/README.md'. Your reference to the SVG image ‘https://vsmarketplacebadge.apphb.com/trending-monthly/lokalise.i18n-ally.svg?color=a1b858’ is not supported. Please see https://aka.ms/vsmarketplace_badge for more details.
open-vsx.org [threw an error](https://github.com/lokalise/i18n-ally/actions/runs/4831679555/jobs/8609433755#step:9:8):
> ❌  SVGs are restricted in README.md; please use other file image formats, such as PNG: https://vsmarketplacebadge.apphb.com/trending-monthly/lokalise.i18 …
> chore: remove SVGs from a README

- package.json
Hi there,
the Fluent project support has been added with the `fluent-vue` support (#651). It works well, but VS Code still issues a warning saying that `ftl`is not a valid parser. It is useful for projects that use Fluent without a specific framework or in another language (Rust).
Thanks for your time
> fix: add ftl as a parser that can be enabled

- src/commands/manipulations/gotoKey.ts
- src/core/loaders/LocaleLoader.ts
Addresses #920 
This fix reverts something that was introduced in #871.
> fix:Re-enable adding strings to the proper namespace

- src/commands/manipulations/newKey.ts
fix of: #817
It seems to be vscode provide arguments a window item to command handler. So I added a validation.
In addition, there was a type error in the `catch` statement, so I added any for now.
> fix: error on create new key

- src/frameworks/svelte.ts
This PR:
1) Fixes #132 for svelte
2) Adds `format` next to `_` and `t` as it's for example [exported](https://github.com/kaisermann/svelte-i18n/blob/0516bb417c4d510e5cd5d225b60cb6ad469118a5/src/runtime/index.ts#L49-L51) in the most popular at the moment i18n library for svelte
3) Adds one more svelte-specific way to handle store. (not by subscribing store via `$`, but using `get` function from `svelte`). `get(_)` usecase may appear when you are trying to get translation outside of svelte component where you can't automatically subscribe with `$`
> svelte: Update usageMatchRegex

- package.json
- src/core/Extract.ts
When using source texts as the keys for translations, a useful feature is to be able to extract the source texts as is.
> feat: allow using the source text as a keygen strategy

- .vscode/settings.json
- locales/en.json
- package.json
- src/core/Config.ts
- src/core/loaders/LocaleLoader.ts
- src/core/types.ts
- src/parsers/base.ts
- src/parsers/json.ts
- src/parsers/yaml.ts
- src/utils/utils.ts
i18n Ally uses a binary sort when it sorts keys. This is unexpected ("O" is sorted before "o") and doesn't take differences in how languages sort things into account.
This change adds two config settings `sortCompare` and `sortLocale`.
- By default `sortCompare` is `binary` which is the current behaviour
- You can set `sortCompare` to `locale` and set `sortLocale` to `en` and keys will be ordered according to English rules for sorting text.
- Alternatively you can set `sortCompare` to `locale` and leave `sortLocale` unspecified and each messages file will be sorted according to its own locale (e.g. `en/common.json` will be sorted using English order, while `es/common.json` will be sorted according to Spanish order).
Fixes #702
> add option to sorting message by a locale's order

- src/core/KeyDetector.ts
- src/editor/completion.ts
This change resolve the following problems
* show auto-complete correctly using a namespace with useTranslation and other specify namespace
Structure
```
locales/
en/
common.json
login.json
ja/
common.json
login.json
```
login.json
```json
{
"emailAddress": "Email Address",
"password": "password",
"rememberMe": "Remember me",
"loginButton": "Sign in",
"socialLoginButton": "Sign in with {{provider}}"
}
```
❌
✅
> fix(react-i18next): show sub completion items when using scoped namespace

- src/frameworks/svelte.ts
Resolves #995
Fix invalid regex introduced in #826
I screwed up with with the syntax :)
For some reason you need to use double backslash `\` to escape symbols like `(` and `s`.
That differs from usual regex syntax that regexper accepts for example.
> fix: invalid Svelte regex

- src/frameworks/svelte.ts
Fixes #1003
According to https://github.com/lokalise/i18n-ally/wiki/Custom-Framework `({key})` in regex should be first capturing group. I did not know about this when proposed #826, #1001
I guess it would be really nice to have tests for regular expressions as it's in the core of i18n-ally.
Maybe at least we can add this info in the comment above this one?
```
// for visualize the regex, you can use https://regexper.com/
```
Knowing that you **must** capture `({key})` as the first group is much more useful than knowing how to visualize regex. If you don't mind, I would like to open another PR which will add comments about this in every framework file, because the only place where I found this is [wiki/Custom-Framework](https://github.com/lokalise/i18n-ally/wiki/Custom-Framework)
> fix: Svelte regex wrong first capturing group (#1003)

- src/frameworks/next-intl.ts
Fixes #1011
Add detection of optional line breaks and spaces for each regex in usageMatchRegex (next-intl)
<details>
<summary>Screenshots</summary>
Before:
After: 
</details>
> fix: next-intl support multilines key detection (#1011)

- examples/by-frameworks/next-intl/messages/de.json
- examples/by-frameworks/next-intl/messages/en.json
- examples/by-frameworks/next-intl/next.config.js
- examples/by-frameworks/next-intl/package.json
- examples/by-frameworks/next-intl/src/app/[locale]/layout.tsx
- examples/by-frameworks/next-intl/src/app/[locale]/page.tsx
- examples/by-frameworks/next-intl/src/i18n.ts
- src/frameworks/next-intl.ts
See Server Components implementation of [Metadata API support](https://next-intl-docs.vercel.app/docs/environments/metadata-route-handlers#metadata-api) 
From https://github.com/lokalise/i18n-ally/issues/1011#issuecomment-1717075869
> feat: Support `getTranslator` API from `next-intl`

- examples/by-frameworks/next-intl/package.json
- examples/by-frameworks/next-intl/src/app/[locale]/GetTranslationsTest1.tsx
- examples/by-frameworks/next-intl/src/app/[locale]/GetTranslationsTest2.tsx
- examples/by-frameworks/next-intl/src/app/[locale]/GetTranslationsTest3.tsx
- examples/by-frameworks/next-intl/src/app/[locale]/UseTranslationsTest1.tsx
- examples/by-frameworks/next-intl/src/app/[locale]/UseTranslationsTest2.tsx
- examples/by-frameworks/next-intl/src/app/[locale]/page.tsx
- src/frameworks/next-intl.ts
Adds support for:
- `getTranslations`
- `t.markup`
Thanks!
> feat: Update `next-intl` to support latest release

- package.json
- webpack.config.js
- yarn.lock
I need support for the `import { type MyType } from 'package';` Typescript feature. That was added to babel in 2.16.0.
I noticed dependabot already opened an PR to upgrade but the build failed. I started with that branch, redid the upgrade to use `7.23.5`, and added the webpack config change needed to make it build.
This should obsolete https://github.com/lokalise/i18n-ally/pull/1033
> fix: upgrade babel to 7.23.5
